package com.reroleresource.mapper;

import com.reroleresource.entity.ReRoleResources;
import com.reroleresource.entity.ReRoleResourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReRoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    long countByExample(ReRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int deleteByExample(ReRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int insert(ReRoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int insertSelective(ReRoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    List<ReRoleResources> selectByExample(ReRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    ReRoleResources selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReRoleResources record, @Param("example") ReRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int updateByExample(@Param("record") ReRoleResources record, @Param("example") ReRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int updateByPrimaryKeySelective(ReRoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 19:51:10 CST 2017
     */
    int updateByPrimaryKey(ReRoleResources record);
}