package com.reuserrole.mapper;

import com.reuserrole.entity.ReUserRole;
import com.reuserrole.entity.ReUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    long countByExample(ReUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int deleteByExample(ReUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int insert(ReUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int insertSelective(ReUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    List<ReUserRole> selectByExample(ReUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    ReUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReUserRole record, @Param("example") ReUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int updateByExample(@Param("record") ReUserRole record, @Param("example") ReUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(ReUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 19:50:24 CST 2017
     */
    int updateByPrimaryKey(ReUserRole record);
}